namespace CebuUpskilling.Backend.Services;

/// <summary>
/// Static fallback skill catalog used until a real upstream API exists
/// (see <see cref="ApiSkillsSource"/>). Names are de-duplicated and normalized
/// by <see cref="SkillsSeedService"/> before insert, so this list only needs to
/// be complete — not perfectly clean.
/// </summary>
public static class StaticSkillsCatalog
{
    public static readonly string[] Names =
    [
        "3D Modelling",
        "Aerodynamics Principles Application",
        "Aerospace Engineering Drawing Interpretation And Management",
        "Air Conditioning And Mechanical Ventilation System Design",
        "Air Conditioning And Mechanical Ventilation Systems Maintenance",
        "Aircraft Communication Systems Maintenance",
        "Aircraft Hydraulic Components Maintenance",
        "Aircraft Navigation And Radar Equipment Maintenance",
        "Aircraft Pneumatic Components Maintenance",
        "Analytical Method Validation",
        "Apply Containment Principles In Laboratory Design",
        "Artificial Intelligence Application",
        "Automated Food Manufacturing System Maintenance",
        "Automated Operation Monitoring",
        "Automated Process Design",
        "Autonomous Systems Technology Application",
        "Battery Systems Design Management",
        "CCTV Pipeline Assessment",
        "Cable Damage Prevention Management",
        "Cargo System Design",
        "Chemical Processing",
        "Civil And Structural Engineering Management",
        "Cleaning And Sterilising",
        "Cleaning Validation",
        "Cleanliness And Contamination Control",
        "Commissioning Coordination",
        "Communication And Navigation System Design",
        "Composite Structures Design And Maintenance",
        "Computational Design",
        "Computer Numeric Control Operations",
        "Computer-Aided Design",
        "Computerised Systems Validation",
        "Condition Monitoring",
        "Construction Project Management",
        "Construction Technology",
        "Control Room Operations Management",
        "Corrective Maintenance Management",
        "Design For Maintainability",
        "Design For Safety",
        "Design for Additive Manufacturing",
        "Digital Techniques Application",
        "Document Control",
        "Dry Dock Project Management",
        "Electric Vehicle And/Or Hybrid Electric Vehicle Charging Management",
        "Electrical And Electronic Systems Maintenance",
        "Electrical Design Approval",
        "Electrical Systems Design",
        "Electrical Termination, Connection And Measurement",
        "Electrical Testing",
        "Electrical, Electronic And Control Engineering",
        "Emergency Shut-Down And Restart",
        "Engineering Drawing",
        "Engineering Drawing And Design Specifications",
        "Engineering Drawing Interpretation And Management",
        "Engineering Maintenance Management",
        "Engineering Problem Solving",
        "Engineering Project Management",
        "Engineering Safety Standards Interpretation",
        "Engineering Services Procurement Management",
        "Engineering Standards Audit And Assessment",
        "Engineering Support Management",
        "Engines And Components Handling, Inspection And Packing",
        "Equipment And Systems Installation And Commissioning Management",
        "Equipment And Systems Repair",
        "Equipment Breakdown Repair and Maintenance",
        "Equipment Drawing",
        "Equipment Maintenance",
        "Equipment Maintenance And Housekeeping",
        "Equipment Qualification",
        "Facilities Shut-Down And ReStart",
        "Facility Design",
        "Facility Maintenance",
        "Fire Protection System Design",
        "Food And Beverage Equipment Maintenance",
        "Food And Beverage Quality Assurance Framework Development",
        "Food Safety Management",
        "Forming",
        "Front-End Engineering Design Management",
        "Fuel Accessories Components Maintenance",
        "Fuel And Lubrication System Design",
        "Gas Meter Installation And Commissioning",
        "Gas Receiving And Holder Operations And Maintenance",
        "Heating, Ventilation And Air Conditioning System Design",
        "High Voltage Direct Current System Operations and Maintenance",
        "High Voltage Power Systems Maintenance",
        "Hull Inspections",
        "Inspection Engineering Management",
        "Installation And Assembly",
        "Installation Planning And Execution",
        "Instrumentation And Control System Design",
        "Interface Management",
        "Laboratory Equipment Maintenance And Calibration Management",
        "Lift Planning And Management",
        "Lightning Protection Systems Design",
        "Low Voltage Power Systems Maintenance",
        "Low Voltage Switchboard Maintenance",
        "Maintenance And Repair",
        "Maintenance Coordination",
        "Maintenance Scheduling",
        "Maintenance Strategy Development",
        "Maintenance Strategy Management",
        "Manufacturing Operation Management",
        "Manufacturing Process Management",
        "Manufacturing Technology",
        "Manufacturing Workflow Management",
        "Marine Design Customisation",
        "Marine Equipment And System Maintenance",
        "Marine Equipment Material Selection",
        "Marine Survey Reporting",
        "Material Handling Equipment (Mhe) Handling",
        "Material Qualification",
        "Material Studies And Production Processes",
        "Mathematical Concepts Application",
        "Measurement Of Building And Construction Works",
        "Mechanical Engineering Management",
        "Mechanical Maintenance Management",
        "Mechanical Rotating Equipment Engineering Management",
        "Mechanical Static Equipment Engineering Management",
        "Metal-Based Additive Manufacturing",
        "Mobile Generator Deployment",
        "Multi-Function Vehicle Maintenance",
        "Nacelle Mechanical Structures Maintenance",
        "Naval Architecture Calculations",
        "New Product Introduction",
        "Non-Destructive Testing (Radiographic Inspection)",
        "Packaging Validation",
        "Perform Basic Maintenance Works",
        "Perform Formwork Activities",
        "Perform Refractory Work",
        "Pharmaceutical And Nutritional Product Introduction",
        "Power Generation System Design",
        "Power Plant Incident Investigation Management",
        "Power Plant Operations Management",
        "Precision Measurement",
        "Preventive Maintenance Management",
        "Process Integration",
        "Process Monitoring",
        "Process Optimisation",
        "Process Plant And Equipment Integrity Management",
        "Process Unit And Utilities Operations Management",
        "Process Validation",
        "Procurement For Production Operations",
        "Product Improvement",
        "Production Operations",
        "Production Optimisation",
        "Production Planning And Scheduling",
        "Propulsion System Design",
        "Quality Assurance",
        "Quality Control And Assurance",
        "Quality Control Mangement",
        "Relay And Protection Systems Development",
        "Reliability Centred Maintenance",
        "Rigging And Signalling",
        "Robotic And Automation System Maintenance",
        "Robotic And Automation Technology Application",
        "Ship Maintenance and Repair at Docks",
        "Ship Propulsion Inspections",
        "Ship Repair Management",
        "Site Assessment And Analysis",
        "Solar Photovoltaic Systems Designs",
        "Sterile Manufacturing Of Pharmaceutical Products",
        "Structural And Arrangement Drawing",
        "Sub-sea Engineering Management",
        "Substation Design Development",
        "Surface Preparation And Protection",
        "Technical Drawing",
        "Technical Inspection",
        "Technical Services Management",
        "Track Tamping Vehicle Maintenance",
        "Utilities Management",
        "Value Analysis",
        "Value Engineering",
        "Ventilation System Maintenance",
        "Video Surveillance System Maintenance",
        "Water Storage System Inspection And Maintenance Management",
        "Workshop Practices Application",
        "Account Management",
        "Accounting Standards",
        "Airline Distribution Channel Strategies",
        "Audit And Compliance",
        "Audit And Review Management",
        "Audit Compliance",
        "Audit Frameworks",
        "Behavioural Economics In Design",
        "Brand Guideline Development",
        "Brand Management",
        "Brand Storytelling",
        "Budgeting",
        "Business Acumen",
        "Business Analysis Management",
        "Business Development Networking",
        "Business Environment Analysis",
        "Business Excellence",
        "Business Innovation",
        "Business Innovation And Improvement",
        "Business Insights",
        "Business Needs Analysis",
        "Business Negotiation",
        "Business Networking",
        "Business Opportunities Development",
        "Business Performance Management",
        "Business Planning",
        "Business Relationship Building",
        "Business-to-Business Customer Relationship Management",
        "Cash Flow Reporting",
        "Conceptual Thinking",
        "Content Development And Strategy",
        "Content Marketing Strategy",
        "Content Strategy",
        "Contract And Vendor Management",
        "Contract Preparation, Evaluation, Negotiation And Tendering",
        "Contracts and Agreement",
        "Corporate Governance",
        "Creative Entrepreneurship",
        "Creative Thinking",
        "Customer Acquisition Management",
        "Customer Management",
        "Decision Making",
        "Demand And Supply Analysis",
        "Display Creation And Management",
        "Disruption Management",
        "Employer Branding",
        "Energy Product Advisory",
        "Energy Product Performance Management",
        "Energy Trading Portfolio Optimisation",
        "Engagement Completion And Reporting",
        "Engagement Execution",
        "Engagement Planning",
        "Engagement Quality Control",
        "Family Governance",
        "Financial Acumen",
        "Financial Analysis",
        "Financial Budgeting",
        "Financial Performance Analysis",
        "Financial Planning",
        "Financial Planning and Budget Management",
        "Financial Reporting Quality",
        "Financial Statements Analysis",
        "Financial Transactions",
        "Freight Rate Hedging Management",
        "Fund Accounting",
        "Game-Based Marketing",
        "Global Perspective",
        "Hedging Management",
        "House Brand Development",
        "Inbound Marketing",
        "Influence",
        "Insurance Claims Handling",
        "Intellectual Property Management",
        "Intellectual Property Management Processes",
        "Intellectual Property Portfolio Management",
        "Internal Controls In Product Development",
        "Investment Financial Modelling",
        "Legal And Compliance Management",
        "Management Decision Making",
        "Market Evaluation",
        "Market Intelligence",
        "Market Research",
        "Market Research And Analysis",
        "Market Specialisation",
        "Market Trend Analysis",
        "Marketing Campaign Management",
        "Marketing Management",
        "Marketing Strategy",
        "Mass Communications Management",
        "Networking",
        "Omni-channel Strategy and Management",
        "Operational Risk Management",
        "Organisational and Reglatory Governance",
        "Paid Search Engine Marketing (Sem)",
        "Partnership Development And Management",
        "Partnership Management",
        "Patent Filing and Registration",
        "Patent Practice",
        "Philanthropy Advisory",
        "Point-Of-Purchase Marketing",
        "Portfolio Management",
        "Post Trade Monitoring And Risk And Capital Management",
        "Price Verification And Profit Analysis",
        "Pricing Strategy",
        "Product Advisory",
        "Product Advisory for Sales and Marketing",
        "Product And Pricing Analysis",
        "Product Costing And Pricing",
        "Product Demonstration",
        "Product Development",
        "Product Management",
        "Product, Content And Experience Performance Management",
        "Products And Services Promotions",
        "Professional Scepticism And Judgment",
        "Programme And Project Management",
        "Programme Evaluation",
        "Programme Management",
        "Programme Planning",
        "Project Administration",
        "Project Coordination",
        "Project Cost",
        "Project Feasibility Assessment",
        "Project Integration",
        "Project Management",
        "Project Plan",
        "Project Resources",
        "Project Scope",
        "Project Timeline",
        "Proposal Management",
        "Registered Design Application",
        "Regulatory Compliance",
        "Regulatory Strategy",
        "Regulatory Submission And Clearance",
        "Research Findings Communication",
        "Research Into Professional Practice Translation",
        "Research Proposal Development",
        "Retail Administration",
        "Retailing And The Economy",
        "Revenue Optimisation",
        "Risk And Compliance Management",
        "Risk And Compliance Reporting",
        "Risk Assessment",
        "Risk Management",
        "Risk Management And Administration",
        "Risk Management and Mitigation",
        "Room Distribution Channel Management",
        "Room Revenue Management",
        "Sales Closure",
        "Sales Management",
        "Sales Performance Management",
        "Sales Strategy",
        "Sales Target Management",
        "Search Engine Optimisation (SEO)",
        "Service Brand",
        "Service Leadership",
        "Service Partnerships",
        "Ship Sale And Purchase",
        "Shipping Trade Management",
        "Shopper Marketing Campaign Management",
        "Social Media Marketing",
        "Solar Photovoltaic Project Financing And Risk Analysis",
        "Solutioning",
        "Solutions Design Thinking",
        "Stakeholder Engagement And Management",
        "Stakeholder Management",
        "Strategic Business Planning",
        "Strategy Development",
        "Strategy Development And Implementation Management",
        "Strategy Execution",
        "Supplier Sourcing",
        "Taxonomy Application",
        "Technical Analysis",
        "Technical Sales Support",
        "Technical Writing",
        "Technology Assessment",
        "Trade Processing, Fund Settlement And Treasury Transaction Processing",
        "Trading Analysis",
        "Transaction Documentation For Prospectus Development",
        "Trend Forecasting",
        "Trust Structuring",
        "Underwriting Process",
        "Vendor And Partnership Management",
        "Vendor Management",
        "Vessel Cost Management",
        "Air-freight Tracking System Adminsitration",
        "Aircraft Cruise Operations",
        "Aircraft Landing Operations",
        "Aircraft Load Planning",
        "Aircraft Manual Handling",
        "Aircraft Weight And Balance Calculation",
        "Airport Safeguarding And Security",
        "Airside Safety",
        "Animal Husbandry And Nutrition",
        "Animal Transaction",
        "Applied Research And Development Management",
        "Apply Workplace Safety And Health In Logistics And Transportation",
        "Apply Workplace Safety and Health Practices",
        "Asset Integrity Management",
        "Asset Management",
        "Attractions Membership, Admission And Ticketing Management",
        "Automated Distribution Management",
        "Automation Design",
        "Automation Research And Implementation",
        "Autonomous Logistics Design And Application",
        "Aviation Accident And Incident Response Management",
        "Baggage Loading And Unloading Administration",
        "Baggage Security Screening Operations",
        "Baggage Services Management",
        "Behavioural Safety Management",
        "Billing And Settlement Administration",
        "Billing Enquiry Management",
        "Billing Procedure",
        "Billing Process Improvement Management",
        "Biological Hazards Management",
        "Biorisk Management",
        "Bulk Cargo Administration",
        "Business-to-Consumer Management",
        "Cabin Safety Management",
        "Call Centre Management",
        "Carbon Accounting",
        "Carbon Footprint Management",
        "Carbon Markets And Decarbonisation Strategies Management",
        "Cargo And Receipt Inspection",
        "Cargo Handling And Stowage",
        "Cargo Issuance And Dispatch",
        "Cargo Lifting",
        "Cargo Load Planning",
        "Cargo Loading And Unloading Administration",
        "Cargo Processing for Air-freight",
        "Cargo Tracking System Administration",
        "Centre Operations Management",
        "Chemical Risk Management",
        "Child Safety And Protection",
        "Cleaning Chemical Handling",
        "Climate Change Management",
        "Clinical Records Documentation And Management",
        "Clinical Support For Patient Service Associates",
        "Confined Space Work",
        "Container Loading And Unloading Administration",
        "Container Operations",
        "Contingency Management",
        "Continuous Improvement Management",
        "Continuous Process Improvement",
        "Continuous Quality Improvement",
        "Cost Control and Management",
        "Cross Docking",
        "Crowd Control And Planning",
        "Crowd Management",
        "Customer Challenges Management",
        "Customer Experience Innovation",
        "Customer Service Delivery",
        "Customer Service Excellence",
        "Dangerous Goods Management in Air Transportation",
        "Delivery Management",
        "Dental Inventory Maintenance And Management",
        "Department Performance Management",
        "Deterrence",
        "Dispute Settlement",
        "Document Management For Pharmacy Support",
        "Documentation And Administration",
        "Drug Distribution And Inventory Management",
        "Ecology In Landscapes",
        "Emergency Management",
        "Emergency Response And Crisis Management",
        "Emergency Response And Crisis Management Development And Implementation",
        "Emergency Response Planning",
        "Emergency and Crisis Situation Management",
        "Environment And Social Governance",
        "Environment Observation",
        "Environmental Protection Management",
        "Environmental Sustainability Management",
        "Equipment And Inventory Management",
        "Equipment And Systems Testing",
        "Ergonomics Hazards Management",
        "Event Logistics Administration",
        "Events Planning And Management",
        "Failure Analysis",
        "Fleet Procurement",
        "Flight Deck Communications",
        "Food And Beverage Inventory Management",
        "Food And Beverage Safety, Hygiene And Security",
        "Food Manufacturing Quality Control Management",
        "Food Waste Disposal And Reduction",
        "Food Waste Management",
        "Freight And Cargo Claim Administration",
        "Front Office Operations Management",
        "Frontline Services Management",
        "Furniture And Furnishing Maintenance",
        "General Waste And Recyclable Waste Collection And Management",
        "Good Agriculture Practices Implementation",
        "Good Manufacturing Practices Implementation",
        "Green Manufacturing Design And Implementation",
        "Green Ship Design",
        "Hazardous Material Management",
        "Hazards Identification",
        "Health And Safety",
        "Health, Safety And Environment Procedures Implementation",
        "Heavy Lifting Machinery Operation",
        "Horizontal Surface Maintenance",
        "Human Factors In Job Design",
        "Implement Incident Management Process",
        "Incident And Accident Investigation",
        "Incident Response",
        "Inclement Weather Operations And Planning",
        "Indoor Air Quality Management",
        "Indoor Environmental Quality Improvement",
        "Infection Control",
        "Inventory Control And Equipment Maintenance",
        "Inventory Control And Equipment Maintenance In Rehabilitation Care",
        "Inventory Management",
        "Lashing",
        "Linen And Uniform Room Operations Management",
        "Major Hazard Installation Safety Case Management",
        "Manage Work At Height",
        "Manage Workplace Safety and Health in Construction Sites",
        "Manpower Planning",
        "Marine Incident And Accident Investigations",
        "Maritime Emergency Response Management",
        "Maritime Hazards Identification",
        "Material Management",
        "Monitoring And Surveillance",
        "Navigation Watch",
        "Navigation and Position Determination",
        "Noise And Vibration Monitoring",
        "Non-Financial Industry Sustainability Developments",
        "Operational Planning",
        "Order Fulfilment Administration",
        "Order Processing And Change Request Management",
        "Organisational Resource Management",
        "Perform Stock Control And Housekeeping Operations",
        "Personnel And Equipment Operational Readiness",
        "Port Call Planning",
        "Pricing For Transportation Services And Operations",
        "Problem Identification",
        "Problem Management",
        "Process Improvement",
        "Process Improvement And Optimisation",
        "Process Safety Management Framework Development And Implementation",
        "Procurement",
        "Product Quality Assurance",
        "Production Quality Management",
        "Productivity Improvement",
        "Programme Quality and Audit Management",
        "Property Operations Management",
        "Propulsion, Plant And Machinery",
        "Public Areas Housekeeping Operations Management",
        "Public Hygiene Maintenance",
        "Quality Improvement and Safe Practices",
        "Quality Standards",
        "Quality System Management",
        "Quality Systems",
        "Radioactive Materials And Irradiating Apparatus Management",
        "Research",
        "Resource Management",
        "Respond to Fire Incident in Workplace",
        "Retail Logistics Administration",
        "Safety Integrity Levels Management",
        "Sample Management",
        "Sanitary Plumbing And Drainage Submission Compliance Management",
        "Scheduling And Slot Coordination",
        "Security Audit Management",
        "Security Management",
        "Security Operation Compliance",
        "Security Performance Management",
        "Security Surveillance Management",
        "Self-Defence",
        "Service Challenges",
        "Service Information And Results",
        "Service Innovation",
        "Service Innovation Culture",
        "Service Level Management",
        "Service Planning And Implementation",
        "Service Quality Management",
        "Ship Compliance Management",
        "Ship Operations",
        "Ship Safety Management Systems Audit",
        "Ship Seaworthiness And Pollution Prevention",
        "Shipping Network Operations Management",
        "Skin Exposure Risk Management",
        "Standard Operating Procedures Development",
        "Store Facilities And Housekeeping",
        "Strategic Service Excellence",
        "Structural Testing",
        "Supervise Workplace Safety And Health For Formwork Construction",
        "Sustainability Assurance",
        "Sustainability Management",
        "Sustainability Reporting",
        "Sustainable Engineering",
        "Sustainable Farming Practice Implementation",
        "Switchboard Operations Management",
        "System And Work Process Improvement",
        "Tank Storage Inventory Management",
        "Test Planning",
        "Threat Observation",
        "Time-Sensitive Cargo Delivery Management",
        "Transport Route And Schedule Planning",
        "Transportation Equipment Handling",
        "Transportation Hub/Control Centre Administration",
        "Transportation Route And Schedule Planning",
        "Use Basic Hand Tools And Equipment",
        "Warehouse Automation Application",
        "Warehouse Facility Security Control",
        "Warehouse Inventory Control And Audit",
        "Warehouse Layout Design",
        "Warehouse Maintenance And Housekeeping",
        "Warehouse Management System Administration",
        "Warehouse Performance Measurement",
        "Warehouse Space Utilisation",
        "Warehousing/Cargo-Related Occupational Health And Safety Management",
        "Waste Collection Management",
        "Waste Disposal Management",
        "Waste Sorting Management",
        "Waste Treatment Management",
        "Water Quality Monitoring In Reservoirs And Waterways",
        "Wholesale Transaction Management",
        "Workflow Management",
        "Workplace And Facilities Safety Management",
        "Workplace First-Aid",
        "Workplace Safety And Health",
        "Workplace Safety And Health Audit System Management",
        "Workplace Safety And Health Culture Management",
        "Workplace Safety And Health For Confined Spaces",
        "Workplace Safety And Health For Electrical Safety",
        "Workplace Safety And Health For Incident And Accident Investigation",
        "Workplace Safety And Health For Marine Mechanical Installation",
        "Workplace Safety And Health Policy Development",
        "Workplace Safety and Health Management in Construction Industry",
        "Workplace Safety and Health Performance Management and Implementation",
        "Workplace Safety and Health Risk Management",
        "Workplace Traffic Safety Management",
        "Applications Development",
        "Applications Support And Enhancement",
        "Billing And Data Risk Management",
        "Business Presentation Delivery",
        "Business Proposal Writing",
        "Cloud Computing Application",
        "Cloud Computing Implementation",
        "Common Data Environment Management",
        "Computer Vision Technology",
        "Confidentiality Management",
        "Configuration Tracking",
        "Cyber And Data Breach Incident Management",
        "Cyber Risk Management",
        "Cybersecurity",
        "Cybersecurity Framework Application",
        "Data Analysis And Interpretation",
        "Data Analytics",
        "Data And Information Visualisation",
        "Data And Statistical Analysis",
        "Data Collection And Analysis",
        "Data Collection And Management",
        "Data Collection And Preparation",
        "Data Engineering",
        "Data Governance",
        "Data Management",
        "Data Protection Management",
        "Data Sharing",
        "Data Storytelling And Visualisation",
        "Data Strategy",
        "Data Synthesis",
        "Data Wrangling",
        "Data and Information Management",
        "Database Administration",
        "Detection And Monitoring Application",
        "Digital Fluency",
        "Documentation",
        "Emerging Technology Synthesis",
        "Enterprise Database System Administration",
        "Evidence Management",
        "Forensic Data Analytics",
        "Game Production Optimisation",
        "Generative AI Model Development",
        "Governance",
        "Idea Generation And Selection",
        "Infocomm Security And Data Privacy",
        "Infographics And Data Visualisation",
        "Information Collection",
        "Information Gathering And Analysis",
        "Infrastructure Design",
        "Infrastructure Support",
        "Intelligent Reasoning",
        "It Standards",
        "Knowledge Management",
        "Operational Technology Security Design",
        "Organisation Representative",
        "Performance Management",
        "Programming And Coding",
        "Prompt Engineering",
        "Proposal Writing",
        "Quantitative Research",
        "Radio Frequency Engineering",
        "Research And Information Synthesis",
        "Research Data Analysis",
        "Scientific Writing And Communication",
        "Security Administration",
        "Security Education And Awareness",
        "Security Governance",
        "Security Strategy",
        "Sense Making",
        "Ship Cyber Security",
        "Software Design",
        "Software Testing",
        "System Configuration Management",
        "Systems Design",
        "Systems Integration",
        "Technical Presentation",
        "Technical Report Writing",
        "Technology Adoption And Innovation",
        "Technology Application",
        "Technology Integration",
        "Threat And Vulnerability Management",
        "Tools Development",
        "Workflow Digitalisation",
    ];
}
