// <auto-generated />
using System;
using CebuUpskilling.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CebuUpskilling.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806035837_AddedPriceFieldToCourse")]
    partial class AddedPriceFieldToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.HasIndex("GenreId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Discipline", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DomainId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("DomainId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DomainId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Natural and applied sciences",
                            Name = "Science"
                        },
                        new
                        {
                            DomainId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Liberal arts and humanities",
                            Name = "Arts"
                        },
                        new
                        {
                            DomainId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer Science, Information Systems, Engineering",
                            Name = "Technology"
                        },
                        new
                        {
                            DomainId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business and management",
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("AnswerKey")
                        .HasColumnType("text");

                    b.Property<int?>("ExerciseContentId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("LessonId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.ExerciseContent", b =>
                {
                    b.Property<int>("ExerciseContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseContentId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<double>("MbSize")
                        .HasColumnType("double precision");

                    b.HasKey("ExerciseContentId");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseContents");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SubDisciplineId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.HasIndex("SubDisciplineId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LearnerId"));

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LearnerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerStudyCourse", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastTotalProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LearnerId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("LearnerStudyCourses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("LessonId");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LessonContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonOrder")
                        .HasColumnType("integer");

                    b.Property<int>("PercentAddedPerContent")
                        .HasColumnType("integer");

                    b.Property<int>("TopicOrder")
                        .HasColumnType("integer");

                    b.HasKey("ContentId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContents");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<double>("MbSize")
                        .HasColumnType("double precision");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MediaId");

                    b.HasIndex("LessonId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PostId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.PostCourseRequired", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("PostCourseRequireds");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Recruiter", b =>
                {
                    b.Property<int>("RecruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecruiterId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RecruiterId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.SubDiscipline", b =>
                {
                    b.Property<int>("SubDisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubDisciplineId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("SubDisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("SubDisciplines");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Course", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Genre", "Genre")
                        .WithMany("Courses")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Exercise", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Lesson", "Lesson")
                        .WithMany("Exercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.ExerciseContent", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Exercise", "Exercise")
                        .WithOne("ExerciseContent")
                        .HasForeignKey("CebuUpskilling.Backend.Entities.ExerciseContent", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Genre", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.SubDiscipline", "SubDiscipline")
                        .WithMany("Genres")
                        .HasForeignKey("SubDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDiscipline");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Learner", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.AppUser", "User")
                        .WithOne("Learner")
                        .HasForeignKey("CebuUpskilling.Backend.Entities.Learner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerStudyCourse", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Course", "Course")
                        .WithMany("LearnerStudyCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.Learner", "Learner")
                        .WithMany("LearnerStudyCourses")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Lesson", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LessonContent", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Media", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Lesson", "Lesson")
                        .WithMany("Media")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Post", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Company", "Company")
                        .WithMany("Posts")
                        .HasForeignKey("CompanyId");

                    b.HasOne("CebuUpskilling.Backend.Entities.Recruiter", "Recruiter")
                        .WithMany("Posts")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.PostCourseRequired", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Course", "Course")
                        .WithMany("PostCourseRequireds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.Post", "Post")
                        .WithMany("PostCourseRequireds")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Recruiter", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Company", "Company")
                        .WithMany("Recruiters")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.AppUser", "User")
                        .WithOne("Recruiter")
                        .HasForeignKey("CebuUpskilling.Backend.Entities.Recruiter", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.SubDiscipline", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Discipline", "Discipline")
                        .WithMany("SubDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.AppUser", b =>
                {
                    b.Navigation("Learner");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Company", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Course", b =>
                {
                    b.Navigation("LearnerStudyCourses");

                    b.Navigation("Lessons");

                    b.Navigation("PostCourseRequireds");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Discipline", b =>
                {
                    b.Navigation("SubDisciplines");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Exercise", b =>
                {
                    b.Navigation("ExerciseContent");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Genre", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Learner", b =>
                {
                    b.Navigation("LearnerStudyCourses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Lesson", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("LessonContents");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Post", b =>
                {
                    b.Navigation("PostCourseRequireds");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Recruiter", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.SubDiscipline", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
