// <auto-generated />
using System;
using CebuUpskilling.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CebuUpskilling.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808123952_AddUserAddress")]
    partial class AddUserAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RemoteFriendly")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.HasIndex("GenreId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Discipline", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DomainId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("DomainId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DomainId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Natural and applied sciences",
                            Name = "Science"
                        },
                        new
                        {
                            DomainId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Liberal arts and humanities",
                            Name = "Arts"
                        },
                        new
                        {
                            DomainId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer Science, Information Systems, Engineering",
                            Name = "Technology"
                        },
                        new
                        {
                            DomainId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business and management",
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("AnswerKey")
                        .HasColumnType("text");

                    b.Property<int?>("ExerciseContentId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("LessonId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.ExerciseContent", b =>
                {
                    b.Property<int>("ExerciseContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseContentId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<double>("MbSize")
                        .HasColumnType("double precision");

                    b.HasKey("ExerciseContentId");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseContents");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SubDisciplineId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.HasIndex("SubDisciplineId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LearnerId"));

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LearnerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerAssessment", b =>
                {
                    b.Property<int>("LearnerAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LearnerAssessmentId"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("LearnerAssessmentId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SkillId");

                    b.ToTable("LearnerAssessments");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerSkill", b =>
                {
                    b.Property<int>("LearnerSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LearnerSkillId"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("LearnerSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("LearnerId", "SkillId")
                        .IsUnique();

                    b.ToTable("LearnerSkills");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerStudyCourse", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastTotalProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LearnerId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("LearnerStudyCourses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("LessonId");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LessonContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonOrder")
                        .HasColumnType("integer");

                    b.Property<int>("PercentAddedPerContent")
                        .HasColumnType("integer");

                    b.Property<int>("TopicOrder")
                        .HasColumnType("integer");

                    b.HasKey("ContentId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContents");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<double>("MbSize")
                        .HasColumnType("double precision");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MediaId");

                    b.HasIndex("LessonId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PostId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.PostCourseRequired", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("PostCourseRequireds");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Recruiter", b =>
                {
                    b.Property<int>("RecruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecruiterId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RecruiterId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.RoleSkill", b =>
                {
                    b.Property<int>("RoleSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleSkillId"));

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleSkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("RoleSkills");

                    b.HasData(
                        new
                        {
                            RoleSkillId = 1,
                            RequiredLevel = 4,
                            SkillId = 1,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 2,
                            RequiredLevel = 3,
                            SkillId = 2,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 3,
                            RequiredLevel = 4,
                            SkillId = 3,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 4,
                            RequiredLevel = 3,
                            SkillId = 4,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 5,
                            RequiredLevel = 4,
                            SkillId = 5,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 6,
                            RequiredLevel = 3,
                            SkillId = 9,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 7,
                            RequiredLevel = 3,
                            SkillId = 10,
                            TargetRole = "Frontend Developer"
                        },
                        new
                        {
                            RoleSkillId = 8,
                            RequiredLevel = 3,
                            SkillId = 1,
                            TargetRole = "Backend Developer"
                        },
                        new
                        {
                            RoleSkillId = 9,
                            RequiredLevel = 4,
                            SkillId = 6,
                            TargetRole = "Backend Developer"
                        },
                        new
                        {
                            RoleSkillId = 10,
                            RequiredLevel = 4,
                            SkillId = 7,
                            TargetRole = "Backend Developer"
                        },
                        new
                        {
                            RoleSkillId = 11,
                            RequiredLevel = 4,
                            SkillId = 8,
                            TargetRole = "Backend Developer"
                        },
                        new
                        {
                            RoleSkillId = 12,
                            RequiredLevel = 3,
                            SkillId = 9,
                            TargetRole = "Backend Developer"
                        },
                        new
                        {
                            RoleSkillId = 13,
                            RequiredLevel = 4,
                            SkillId = 10,
                            TargetRole = "Backend Developer"
                        },
                        new
                        {
                            RoleSkillId = 14,
                            RequiredLevel = 4,
                            SkillId = 1,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 15,
                            RequiredLevel = 3,
                            SkillId = 2,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 16,
                            RequiredLevel = 3,
                            SkillId = 3,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 17,
                            RequiredLevel = 4,
                            SkillId = 6,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 18,
                            RequiredLevel = 3,
                            SkillId = 8,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 19,
                            RequiredLevel = 3,
                            SkillId = 9,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 20,
                            RequiredLevel = 4,
                            SkillId = 10,
                            TargetRole = "Full Stack Developer"
                        },
                        new
                        {
                            RoleSkillId = 21,
                            RequiredLevel = 4,
                            SkillId = 7,
                            TargetRole = "Data Analyst"
                        },
                        new
                        {
                            RoleSkillId = 22,
                            RequiredLevel = 5,
                            SkillId = 8,
                            TargetRole = "Data Analyst"
                        },
                        new
                        {
                            RoleSkillId = 23,
                            RequiredLevel = 2,
                            SkillId = 1,
                            TargetRole = "Data Analyst"
                        },
                        new
                        {
                            RoleSkillId = 24,
                            RequiredLevel = 5,
                            SkillId = 7,
                            TargetRole = "Data Scientist"
                        },
                        new
                        {
                            RoleSkillId = 25,
                            RequiredLevel = 4,
                            SkillId = 8,
                            TargetRole = "Data Scientist"
                        },
                        new
                        {
                            RoleSkillId = 26,
                            RequiredLevel = 3,
                            SkillId = 1,
                            TargetRole = "Data Scientist"
                        },
                        new
                        {
                            RoleSkillId = 27,
                            RequiredLevel = 5,
                            SkillId = 15,
                            TargetRole = "UI/UX Designer"
                        },
                        new
                        {
                            RoleSkillId = 28,
                            RequiredLevel = 4,
                            SkillId = 4,
                            TargetRole = "UI/UX Designer"
                        },
                        new
                        {
                            RoleSkillId = 29,
                            RequiredLevel = 4,
                            SkillId = 5,
                            TargetRole = "UI/UX Designer"
                        },
                        new
                        {
                            RoleSkillId = 30,
                            RequiredLevel = 5,
                            SkillId = 13,
                            TargetRole = "DevOps Engineer"
                        },
                        new
                        {
                            RoleSkillId = 31,
                            RequiredLevel = 4,
                            SkillId = 14,
                            TargetRole = "DevOps Engineer"
                        },
                        new
                        {
                            RoleSkillId = 32,
                            RequiredLevel = 4,
                            SkillId = 9,
                            TargetRole = "DevOps Engineer"
                        },
                        new
                        {
                            RoleSkillId = 33,
                            RequiredLevel = 3,
                            SkillId = 1,
                            TargetRole = "Quality Assurance"
                        },
                        new
                        {
                            RoleSkillId = 34,
                            RequiredLevel = 3,
                            SkillId = 9,
                            TargetRole = "Quality Assurance"
                        },
                        new
                        {
                            RoleSkillId = 35,
                            RequiredLevel = 2,
                            SkillId = 8,
                            TargetRole = "Quality Assurance"
                        });
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Category = "Language",
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = 2,
                            Category = "Language",
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = 3,
                            Category = "Framework",
                            Name = "React"
                        },
                        new
                        {
                            SkillId = 4,
                            Category = "Language",
                            Name = "CSS"
                        },
                        new
                        {
                            SkillId = 5,
                            Category = "Language",
                            Name = "HTML"
                        },
                        new
                        {
                            SkillId = 6,
                            Category = "Runtime",
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = 7,
                            Category = "Language",
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = 8,
                            Category = "Language",
                            Name = "SQL"
                        },
                        new
                        {
                            SkillId = 9,
                            Category = "Tool",
                            Name = "Git"
                        },
                        new
                        {
                            SkillId = 10,
                            Category = "Concept",
                            Name = "REST APIs"
                        },
                        new
                        {
                            SkillId = 11,
                            Category = "Framework",
                            Name = "Vue.js"
                        },
                        new
                        {
                            SkillId = 12,
                            Category = "Framework",
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = 13,
                            Category = "Tool",
                            Name = "Docker"
                        },
                        new
                        {
                            SkillId = 14,
                            Category = "Platform",
                            Name = "AWS"
                        },
                        new
                        {
                            SkillId = 15,
                            Category = "Tool",
                            Name = "Figma"
                        });
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.SubDiscipline", b =>
                {
                    b.Property<int>("SubDisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubDisciplineId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("SubDisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("SubDisciplines");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Course", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Genre", "Genre")
                        .WithMany("Courses")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Exercise", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Lesson", "Lesson")
                        .WithMany("Exercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.ExerciseContent", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Exercise", "Exercise")
                        .WithOne("ExerciseContent")
                        .HasForeignKey("CebuUpskilling.Backend.Entities.ExerciseContent", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Genre", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.SubDiscipline", "SubDiscipline")
                        .WithMany("Genres")
                        .HasForeignKey("SubDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDiscipline");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Learner", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.AppUser", "User")
                        .WithOne("Learner")
                        .HasForeignKey("CebuUpskilling.Backend.Entities.Learner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerAssessment", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Learner", "Learner")
                        .WithMany("LearnerAssessments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerSkill", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Learner", "Learner")
                        .WithMany("LearnerSkills")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.Skill", "Skill")
                        .WithMany("LearnerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LearnerStudyCourse", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Course", "Course")
                        .WithMany("LearnerStudyCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.Learner", "Learner")
                        .WithMany("LearnerStudyCourses")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Lesson", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.LessonContent", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Media", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Lesson", "Lesson")
                        .WithMany("Media")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Post", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Company", "Company")
                        .WithMany("Posts")
                        .HasForeignKey("CompanyId");

                    b.HasOne("CebuUpskilling.Backend.Entities.Recruiter", "Recruiter")
                        .WithMany("Posts")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.PostCourseRequired", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Course", "Course")
                        .WithMany("PostCourseRequireds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.Post", "Post")
                        .WithMany("PostCourseRequireds")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Recruiter", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Company", "Company")
                        .WithMany("Recruiters")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuUpskilling.Backend.Entities.AppUser", "User")
                        .WithOne("Recruiter")
                        .HasForeignKey("CebuUpskilling.Backend.Entities.Recruiter", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.RoleSkill", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Skill", "Skill")
                        .WithMany("RoleSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.SubDiscipline", b =>
                {
                    b.HasOne("CebuUpskilling.Backend.Entities.Discipline", "Discipline")
                        .WithMany("SubDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.AppUser", b =>
                {
                    b.Navigation("Learner");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Company", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Course", b =>
                {
                    b.Navigation("LearnerStudyCourses");

                    b.Navigation("Lessons");

                    b.Navigation("PostCourseRequireds");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Discipline", b =>
                {
                    b.Navigation("SubDisciplines");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Exercise", b =>
                {
                    b.Navigation("ExerciseContent");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Genre", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Learner", b =>
                {
                    b.Navigation("LearnerAssessments");

                    b.Navigation("LearnerSkills");

                    b.Navigation("LearnerStudyCourses");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Lesson", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("LessonContents");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Post", b =>
                {
                    b.Navigation("PostCourseRequireds");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Recruiter", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.Skill", b =>
                {
                    b.Navigation("LearnerSkills");

                    b.Navigation("RoleSkills");
                });

            modelBuilder.Entity("CebuUpskilling.Backend.Entities.SubDiscipline", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
